name: Yarn Audit Fix and PR

on:
  workflow_call:
    inputs:
      base_branch:
        required: false
        type: string
        default: "main"
      pr_title:
        required: false
        type: string
        default: "fix: Apply Yarn audit fix"
      pr_body:
        required: false
        type: string
        default: "This PR applies security updates via `yarn-audit-fix`."

permissions:
  contents: write
  pull-requests: write

jobs:
  yarn-audit-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set Up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Yarn Audit Fix (Third-Party)
        run: |
          npx yarn-audit-fix || echo "No fixes needed"

      - name: Build Project
        run: |
          if yarn run | grep -q "build"; then
            yarn build
          else
            echo "No build script found, skipping build step."
          fi


      - name: Check for Changes
        id: check_changes
        run: |
          git add .
          if git diff --cached --exit-code; then
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Configure Git
        if: env.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Branch
        if: env.changes == 'true'
        run: |
          BRANCH_NAME="yarn-audit-fix-$(date +'%Y-%m-%d-%H-%M-%S')"
          git checkout -b "$BRANCH_NAME"
          git commit -m "fix: apply Yarn audit fix"
          git push origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.changes == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: process.env.BRANCH_NAME,
              base: "${{ inputs.base_branch }}",
              title: "${{ inputs.pr_title }}",
              body: "${{ inputs.pr_body }}",
              draft: false
            });

            console.log(`Pull Request created: ${pr.html_url}`);
